// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrddEWuC2BIHrLQaaORMYh1UfzmSee07Y',
    appId: '1:13353119708:web:31b22a992ce7f11bafa919',
    messagingSenderId: '13353119708',
    projectId: 'payflow-nlw-rocketseat-e776d',
    authDomain: 'payflow-nlw-rocketseat-e776d.firebaseapp.com',
    storageBucket: 'payflow-nlw-rocketseat-e776d.appspot.com',
    measurementId: 'G-J6R35S33D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz2MtvJEAy1Gx272sOOae6BxJQrkvQAko',
    appId: '1:13353119708:android:f2cb1ef2d130a070afa919',
    messagingSenderId: '13353119708',
    projectId: 'payflow-nlw-rocketseat-e776d',
    storageBucket: 'payflow-nlw-rocketseat-e776d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABwkKgVm6QUmymxn2emrnpVJNCqzOBoFw',
    appId: '1:13353119708:ios:81dd215dd006b601afa919',
    messagingSenderId: '13353119708',
    projectId: 'payflow-nlw-rocketseat-e776d',
    storageBucket: 'payflow-nlw-rocketseat-e776d.appspot.com',
    androidClientId: '13353119708-lbia4eaf91ccubou1ldukav0vqhgbu6d.apps.googleusercontent.com',
    iosClientId: '13353119708-54jhsicrogs56t38ifilhpb28msln9pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.iosApp',
  );
}
